services:
  todo-bot:
    image: theucp/todo-bot
    container_name: todo-bot
    environment:
      - token=<token>
    volumes:
      - /home/discord/todo-data:/Todo/userdata
    restart: unless-stopped